# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20170602_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='entities',
            field=models.ManyToManyField(related_name='entities', to='drugs.Entities'),
        ),
    ]
